'use strict'

module.exports = {
  GOT_CANCELED_STX            : 'GOT_CANCELED_STX',
  GOT_MAINTAIN_SEED_ORDERS    : 'GOT_MAINTAIN_SEED_ORDERS',
  GOT_MAINTAIN_TRIM_ORDERS    : 'GOT_MAINTAIN_TRIM_ORDERS',
  GOT_TX                      : 'GOT_TX',
  REQ_API_PREPARE_SUBMIT_TX   : 'REQ_API_PREPARE_SUBMIT_TX',
  REQ_API_PREPARE_CANCEL_TX   : 'REQ_API_PREPARE_CANCEL_TX',
  GOT_TX_SUBMITTED_RESPONSE    : 'GOT_TX_SUBMITTED_RESPONSE'
}

